from hdbcli import dbapi

HOST = "10.4.14.30"
PORT = 30015
USER = "CIDBREAD"
PASS = "P@ssw0rd"

def run(label, sql):
    try:
        con = dbapi.connect(address=HOST, port=PORT, user=USER, password=PASS)
        cur = con.cursor()
        cur.execute(sql)
        cols = [d[0] for d in cur.description]
        rows = cur.fetchmany(5)
        print("\n--- " + label + " ---")
        print(" | ".join(cols))
        print("-" * 80)
        for r in rows:
            print(" | ".join(str(x) if x is not None else "null" for x in r))
        print("Rows: " + str(len(rows)))
        con.close()
    except Exception as e:
        print("ERROR in " + label + ": " + str(e))

print("=== DEV (elcmpczapp) HANA ALIGNMENT CHECK ===\n")

# 1. ZEL_CS_OFFERS_MT - DISC_FLAT active offers
run("ACTIVE DISC_FLAT OFFERS",
    "SELECT TOP 5 LTRIM(CON_ID,'0') AS CONTRACT_ID, OFFER_CHARACTERISTICS_VALUE, STATUS, "
    "OFFER_APPLIED_START_DATE, OFFER_APPLIED_END_DATE "
    "FROM SAPHANADB.ZEL_CS_OFFERS_MT "
    "WHERE OFFER_CHARACTERISTICS='DISC_FLAT' "
    "AND (STATUS IS NULL OR STATUS NOT IN ('DEACTIVATED','EXPIRED')) "
    "AND CURRENT_DATE BETWEEN TO_DATE(OFFER_APPLIED_START_DATE,'YYYYMMDD') "
    "AND TO_DATE(OFFER_APPLIED_END_DATE,'YYYYMMDD')")

# 2. ZVEL_CS_MASTER available
run("ACTIVE BASE PLANS",
    "SELECT TOP 3 LTRIM(VTREF,'0') AS CONTRACT_ID, LTRIM(SOLD_TO_PARTY,'0') AS USER_ID, "
    "PLAN_TYPE, STATUS, PLAN_END_DT, VARIANT_NAME "
    "FROM SAPHANADB.ZVEL_CS_MASTER(CURRENT_DATE, CURRENT_TIME) "
    "WHERE PLAN_TYPE='BASE_PLAN' AND STATUS='A'")

# 3. ZEL_EVENT_RAW aligned
run("ZEL_EVENT_RAW COLUMNS CHECK",
    "SELECT TOP 3 CON_ID, CUST_PLAN_NAME, PLAN_PRICE, UPF_INSTALLMENT, "
    "COMMITMENT_VAL, EVENT_TYPE, AMT "
    "FROM SAPHANADB.ZEL_EVENT_RAW "
    "WHERE EVENT_TYPE NOT LIKE '%COMMISSION%'")

# 4. ZEL_NOTIFY - PLAN_EXPIRY today
run("ZEL_NOTIFY PLAN_EXPIRY TODAY",
    "SELECT COUNT(*) AS COUNT, MAX(CREATE_TS) AS LAST_CREATED "
    "FROM SAPHANADB.ZEL_NOTIFY "
    "WHERE NOTIFICATION_TYPE='PLAN_EXPIRY' AND TO_DATE(CREATE_TS)=CURRENT_DATE")

# 5. Our full LEFT JOIN SQL (read-only) from DEV
run("FULL LEFT JOIN SQL - DEV SIDE (READ ONLY)",
    "SELECT TOP 5 LTRIM(T1.SOLD_TO_PARTY,'0') AS USER_ID, "
    "T2.PLAN_PRICE, OFR.OFFER_CHARACTERISTICS_VALUE AS DISC_FLAT, "
    "CAST(GREATEST(0, CAST(T2.PLAN_PRICE AS DECIMAL) "
    "- COALESCE(OFR.OFFER_CHARACTERISTICS_VALUE,0)) AS INT) AS NEW_MONTHLY_COST, "
    "T1.PLAN_END_DT "
    "FROM SAPHANADB.ZVEL_CS_MASTER(CURRENT_DATE, CURRENT_TIME) T1 "
    "INNER JOIN SAPHANADB.ZEL_EVENT_RAW T2 "
    "ON T1.VARIANT_NAME=T2.CUST_PLAN_NAME AND T1.VTREF=T2.CON_ID "
    "LEFT JOIN ( "
    "  SELECT LTRIM(CON_ID,'0') AS CON_ID_KEY, "
    "  MAX(CAST(OFFER_CHARACTERISTICS_VALUE AS DECIMAL)) AS OFFER_CHARACTERISTICS_VALUE "
    "  FROM SAPHANADB.ZEL_CS_OFFERS_MT "
    "  WHERE OFFER_CHARACTERISTICS='DISC_FLAT' "
    "  AND (STATUS IS NULL OR STATUS NOT IN ('DEACTIVATED','EXPIRED')) "
    "  AND CURRENT_DATE BETWEEN TO_DATE(OFFER_APPLIED_START_DATE,'YYYYMMDD') "
    "  AND TO_DATE(OFFER_APPLIED_END_DATE,'YYYYMMDD') "
    "  GROUP BY LTRIM(CON_ID,'0') "
    ") OFR ON LTRIM(T1.VTREF,'0')=OFR.CON_ID_KEY "
    "WHERE T1.PLAN_TYPE='BASE_PLAN' AND T1.STATUS='A' "
    "AND T2.EVENT_TYPE NOT LIKE '%COMMISSION%' "
    "AND T2.EVENT_TYPE<>'CHANGE_DATE' AND T2.EVENT_TYPE<>'PLAN_SCHEDULE' "
    "AND OFR.OFFER_CHARACTERISTICS_VALUE IS NOT NULL")

# 6. Contract expiring tomorrow with offer (key test case)
run("CONTRACT 50440 - EXPIRING TOMORROW WITH OFFER",
    "SELECT LTRIM(T1.VTREF,'0') AS CONTRACT_ID, "
    "LTRIM(T1.SOLD_TO_PARTY,'0') AS USER_ID, "
    "T1.PLAN_END_DT, T2.PLAN_PRICE, "
    "OFR.OFFER_CHARACTERISTICS_VALUE AS DISC_FLAT, "
    "CAST(GREATEST(0, CAST(T2.PLAN_PRICE AS DECIMAL) "
    "- COALESCE(OFR.OFFER_CHARACTERISTICS_VALUE,0)) AS INT) AS EXPECTED_MONTHLY_COST "
    "FROM SAPHANADB.ZVEL_CS_MASTER(CURRENT_DATE, CURRENT_TIME) T1 "
    "INNER JOIN SAPHANADB.ZEL_EVENT_RAW T2 "
    "ON T1.VARIANT_NAME=T2.CUST_PLAN_NAME AND T1.VTREF=T2.CON_ID "
    "LEFT JOIN ( "
    "  SELECT LTRIM(CON_ID,'0') AS CON_ID_KEY, "
    "  MAX(CAST(OFFER_CHARACTERISTICS_VALUE AS DECIMAL)) AS OFFER_CHARACTERISTICS_VALUE "
    "  FROM SAPHANADB.ZEL_CS_OFFERS_MT "
    "  WHERE OFFER_CHARACTERISTICS='DISC_FLAT' "
    "  AND (STATUS IS NULL OR STATUS NOT IN ('DEACTIVATED','EXPIRED')) "
    "  AND CURRENT_DATE BETWEEN TO_DATE(OFFER_APPLIED_START_DATE,'YYYYMMDD') "
    "  AND TO_DATE(OFFER_APPLIED_END_DATE,'YYYYMMDD') "
    "  GROUP BY LTRIM(CON_ID,'0') "
    ") OFR ON LTRIM(T1.VTREF,'0')=OFR.CON_ID_KEY "
    "WHERE LTRIM(T1.VTREF,'0')='50440' "
    "AND T2.EVENT_TYPE NOT LIKE '%COMMISSION%' "
    "AND T2.EVENT_TYPE<>'CHANGE_DATE' AND T2.EVENT_TYPE<>'PLAN_SCHEDULE'")

print("\n=== DEV ALIGNMENT CHECK COMPLETE (READ-ONLY) ===")
